### Prova 1 - Oxetech

#### Nome: Edvaldo Felisberto de Ataide Neto.

## **1. Importação**

Início da importação do arquivo e bibliotecas básicas.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Prova_1_Base_Vendas.csv')

## **2. Inspeção**

Inspeção inicial visando ter uma visão geral da base de dados.

In [ ]:
# head()
# Para ter uma visão de parte dos dados

df.head(10)

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido
0,V0001,2025-02-27,Campinas,SP,Camiseta,Vestuário,3 unidades,79.9,0.00,NaN,Cartão de Crédito,Concluído
1,V0002,2025-01-24,Campinas,SP,Garrafa Térmica,Casa,1,99.9,0.00,99.90,Cartão de Crédito,Concluído
2,V0003,2025-02-26,São Paulo,SP,Mochila,Acessórios,5,159.9,0.10,719.55,Boleto,Cancelado
3,V0004,2025-03-29,Curitiba,PR,Camiseta,Vestuário,2,79.9,0.10,143.82,Cartão de Débito,Concluído
4,V0005,2025-04-08,Belo Horizonte,MG,Mouse,Eletrônicos,1,89.9,0.00,89.90,Pix,Concluído
5,V0006,2025-05-18,Porto Alegre,RS,Fone Bluetooth,Eletrônicos,1,129.9,0.10,116.91,pix,Concluído
6,V0007,2025-05-28,Campinas,SP,Fone Bluetooth,Eletrônicos,5,129.9,0.05,617.02,Cartão de Crédito,Concluído
7,V0008,2025-03-01,São Paulo,SP,Mochila,Acessórios,3,159.9,0.00,479.70,Pix,Concluído
8,V0009,2025-04-05,Curitiba,PR,Caderno,Papelaria,3,29.9,0.00,89.70,Cartão de Débito,Concluído
9,V0010,2025-05-17,Curitiba,PR,Calça Jeans,Vestuário,5,189.9,0.00,949.50,Cartão de Crédito,Concluído

Já é possível ver erros tanto nos tipos de dados quanto em textos escritos...

In [ ]:
# Shape
# Para ter uma leitura das linhas e colunas, respectivamente (linhas, colunas).

df.shape

(488, 12)

Verificamos 488 linhas e 12 colunas.

In [ ]:
# Info
# Para obter informações sobre tipos de dados e nulos

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         488 non-null    object
 1   data_venda       488 non-null    object
 2   cidade           480 non-null    object
 3   estado           488 non-null    object
 4   produto          488 non-null    object
 5   categoria        488 non-null    object
 6   quantidade       488 non-null    object
 7   preco_unitario   488 non-null    float64
 8   desconto_pct     488 non-null    float64
 9   valor_total      478 non-null    float64
 10  forma_pagamento  475 non-null    object
 11  status_pedido    488 non-null    object
dtypes: float64(3), object(9)
memory usage: 45.9+ KB

Graças ao .info() podemos identificar valores vazios em 'cidade', 'valor_total' e 'forma_pagamento'. Além de descobrir que as colunas 'data_venda' e 'quantidade' estão com o tipo de dados errado.

In [ ]:
# isnull()
# Para verificação de valores nulos, complementando a informação obtida com .info()

df.isnull().sum().sort_values(ascending=False)

forma_pagamento    13
valor_total        10
cidade              8
id_venda            0
estado              0
data_venda          0
produto             0
categoria           0
preco_unitario      0
quantidade          0
desconto_pct        0
status_pedido       0
dtype: int64

Dessa forma encontramos com melhor precisão quantos valores nulos existem e em quais colunas eles estão, reafirmando oque foi descoberto com .info().

## **3. Tratamento**

Tratamento da base de dados para garantir análises, cálculos e inspeções eficazes.

### 3.1 Textos inseridos

Verificação e tratamento de textos inseridos.

In [ ]:
# Verificando as colunas de texto
## "cidade", "estado", "produto", "categoria","forma_pagamento", "status_pedido"

colunas_texto = df[["cidade", "estado", "produto", "categoria","forma_pagamento", "status_pedido"]]

for columns in colunas_texto:
  valores_unicos = df[columns].dropna().unique()
  print(f"=== Coluna: {columns} ({len(valores_unicos)} valores distintos) ===")
  print(sorted(valores_unicos))
  print("\n")

=== Coluna: cidade (14 valores distintos) ===
[' Campinas ', ' Curitiba ', ' Porto Alegre ', ' Recife ', ' Rio de Janeiro ', ' São Paulo ', 'Belo Horizonte', 'Campinas', 'Curitiba', 'Porto Alegre', 'Recife', 'Rio de Janeiro', 'Salvador', 'São Paulo']


=== Coluna: estado (7 valores distintos) ===
['BA', 'MG', 'PE', 'PR', 'RJ', 'RS', 'SP']


=== Coluna: produto (8 valores distintos) ===
['Caderno', 'Calça Jeans', 'Camiseta', 'Fone Bluetooth', 'Garrafa Térmica', 'Mochila', 'Mouse', 'Tênis']


=== Coluna: categoria (12 valores distintos) ===
['ACESSÓRIOS', 'Acessórios', 'CALÇADOS', 'CASA', 'Calçados', 'Casa', 'ELETRÔNICOS', 'Eletrônicos', 'PAPELARIA', 'Papelaria', 'VESTUÁRIO', 'Vestuário']


=== Coluna: forma_pagamento (8 valores distintos) ===
['Boleto', 'Cartão de Crédito', 'Cartão de Débito', 'Pix', 'boleto', 'cartão de crédito', 'cartão de débito', 'pix']


=== Coluna: status_pedido (2 valores distintos) ===
['Cancelado', 'Concluído']

Através da célula acima, percebemos que:


*   As colunas: estado, produto e status_pedido possuem seus valores em uma forma aceitável.
*   As demais colunas ("cidade", "categoria", "forma_pagamento") apresentam inconsistências em relação a espaços vazios nos nomes e letras maiúsculas e minúsculas.

Podemos apenas filtrar as bases que precisam desse tratamento.

In [ ]:
colunas_erradas = ["cidade", "categoria", "forma_pagamento"]

df[colunas_erradas] = df[colunas_erradas].apply(lambda x: x.str.strip().str.title())

In [ ]:
# Conferindo...
colunas_texto = df[["cidade", "categoria", "forma_pagamento"]]

for columns in colunas_texto:
  valores_unicos = df[columns].dropna().unique()
  print(f"=== Coluna: {columns} ({len(valores_unicos)} valores distintos) ===")
  print(sorted(valores_unicos))
  print("\n")

=== Coluna: cidade (8 valores distintos) ===
['Belo Horizonte', 'Campinas', 'Curitiba', 'Porto Alegre', 'Recife', 'Rio De Janeiro', 'Salvador', 'São Paulo']


=== Coluna: categoria (6 valores distintos) ===
['Acessórios', 'Calçados', 'Casa', 'Eletrônicos', 'Papelaria', 'Vestuário']


=== Coluna: forma_pagamento (4 valores distintos) ===
['Boleto', 'Cartão De Crédito', 'Cartão De Débito', 'Pix']

### 3.2 Duplicatas

Verificação e tratamento de duplicatas na base de dados.

In [ ]:
# .duplicated()

quant_duplicados = df.duplicated().sum()

print(f"Quantos duplicados existem na base de dados: {quant_duplicados}")

Quantos duplicados existem na base de dados: 8

In [ ]:
# Verificando que existem 8 duplicados
# Visualizando elas...

df[df.duplicated(keep=False)].sort_values(by=list(df.columns))

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido
27,V0028,2025-03-13,Porto Alegre,RS,Calça Jeans,Vestuário,5,189.9,0.00,949.50,Boleto,Concluído
485,V0028,2025-03-13,Porto Alegre,RS,Calça Jeans,Vestuário,5,189.9,0.00,949.50,Boleto,Concluído
51,V0052,01/04/2025,Porto Alegre,RS,Mochila,Acessórios,2,159.9,0.00,319.80,Boleto,Cancelado
486,V0052,01/04/2025,Porto Alegre,RS,Mochila,Acessórios,2,159.9,0.00,319.80,Boleto,Cancelado
80,V0081,2025-06-19,São Paulo,SP,Garrafa Térmica,Casa,5,99.9,0.15,424.57,Pix,Concluído
484,V0081,2025-06-19,São Paulo,SP,Garrafa Térmica,Casa,5,99.9,0.15,424.57,Pix,Concluído
84,V0085,2025-03-05,Belo Horizonte,MG,Calça Jeans,Vestuário,1,189.9,0.00,189.90,Cartão De Crédito,Concluído
480,V0085,2025-03-05,Belo Horizonte,MG,Calça Jeans,Vestuário,1,189.9,0.00,189.90,Cartão De Crédito,Concluído
169,V0170,2025-04-28,Belo Horizonte,MG,Camiseta,Vestuário,5,79.9,0.05,379.52,Pix,Concluído
487,V0170,2025-04-28,Belo Horizonte,MG,Camiseta,Vestuário,5,79.9,0.05,379.52,Pix,Concluído
222,V0223,2025-04-06,Recife,PE,Camiseta,Vestuário,4,79.9,0.15,271.66,Cartão De Crédito,Concluído
483,V0223,2025-04-06,Recife,PE,Camiseta,Vestuário,4,79.9,0.15,271.66,Cartão De Crédito,Concluído
310,V0311,2025-04-24,Rio De Janeiro,RJ,Tênis,Calçados,3,249.9,0.15,637.25,Pix,Concluído
481,V0311,2025-04-24,Rio De Janeiro,RJ,Tênis,Calçados,3,249.9,0.15,637.25,Pix,Concluído
455,V0456,2025-04-15,Rio De Janeiro,RJ,Caderno,Papelaria,4,29.9,0.05,113.62,NaN,Cancelado
482,V0456,2025-04-15,Rio De Janeiro,RJ,Caderno,Papelaria,4,29.9,0.05,113.62,NaN,Cancelado

Verificamos que são um caso de linhas idênticas, sendo assim, podemos excluir as duplicatas inteiramente sem prejuízos.

In [ ]:
# Excluindo as duplicatas

df = df.drop_duplicates()

# Verificando o tamanho da base novamente, antes tinhamos 488 linhas.

df.shape

(480, 12)

Agora temos apenas 480 linhas, sem duplicatas.

### 3.3 Tipos de dados
Segundo nossa verificação com .info(), percebemos que quantidade e data estão com erros em seus tipos de dados. Além disso, graças as outras etapas de limpeza anteriores, percebemos erros em seus dados inseridos e formatação.

Sendo assim, trataremos de cada uma dessas colunas separadamente.

#### 3.3.1 Quantidade

In [ ]:
df["quantidade"].dtypes

dtype('O')

Confirmamos, como antes, que a coluna quantidade está com o tipo de dados como 'object', quando o mais adequado seria 'int64'.

In [ ]:
# Verificando valores inseridos...

df["quantidade"].value_counts()

quantidade
1             99
2             96
4             92
3             91
5             91
3 unidades     3
0              3
2 unidades     2
4 unidades     1
1 unidades     1
5 unidades     1
Name: count, dtype: int64

Percebemos que alguns valores inseridos estão com textos escritos.

In [ ]:
# Corrigindo a coluna quantidade...

df["quantidade"] = (
    df["quantidade"]
    .astype(str)
    .str.replace(" unidades", "", regex=False)
    .str.strip()
)

df["quantidade"] = pd.to_numeric(
    df["quantidade"],
    errors="coerce"
)

In [ ]:
# Verificando a coluna quantidade novamente...

df["quantidade"].value_counts()

quantidade
1    100
2     98
3     94
4     93
5     92
0      3
Name: count, dtype: int64

Agora ela está como int64 e com os valores ajustados, mas nota-se um valor a presença de quantidade igual a 0 em 3 casos.
Por se tratar de um parámetro utilizado para calcular o valor de valor_total, devemos utilizar a fórmula do valor_total para saber a quantidade correta que deveria ir ao invés de 0.

**Fórmula:**

`valor_total = (preco_unitario * quantidade) * (1 - desconto_pct)`

In [ ]:
# Separando as quantidades erradas
quantidade_zerada = df[df["quantidade"] == 0]

quantidade_zerada.head()

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido
17,V0018,2025-06-14,São Paulo,SP,Calça Jeans,Vestuário,0,189.9,0.05,902.02,Cartão De Débito,Concluído
409,V0410,2025-04-12,Salvador,BA,Mouse,Eletrônicos,0,89.9,0.15,76.42,Cartão De Crédito,Concluído
433,V0434,2025-01-30,São Paulo,SP,Mochila,Acessórios,0,159.9,0.10,143.91,Boleto,Cancelado

Analisando, percebemos que os valores, exceto quantidade, atingem o esperado. Podemos calcular o quanto deveria ser o valor dessa quantidade.

`quantidade = valor_total / (preco_unitario * (1 - desconto_pct))`

In [ ]:
# Criando uma coluna de comparação ideal
df["quantidade_esperada"] = (
    df["valor_total"] / (df["preco_unitario"] * (1 - df["desconto_pct"]))
)

In [ ]:
# Comparando com o valor ideal
df.loc[
    df["quantidade"] == 0,
    ["quantidade", "quantidade_esperada"]
].round(2)

     quantidade  quantidade_esperada
17            0                  5.0
409           0                  1.0
433           0                  1.0

In [ ]:
# Substituindo pelo valor ideal
df.loc[df["quantidade"] == 0, "quantidade"] = (
    df.loc[df["quantidade"] == 0, "quantidade_esperada"].round().astype(int)
)

In [ ]:
# Localizando as antigas linhas
indices_corrigidos = [17, 409, 433]

df.loc[indices_corrigidos]

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido,quantidade_esperada
17,V0018,2025-06-14,São Paulo,SP,Calça Jeans,Vestuário,5,189.9,0.05,902.02,Cartão De Débito,Concluído,4.999972
409,V0410,2025-04-12,Salvador,BA,Mouse,Eletrônicos,1,89.9,0.15,76.42,Cartão De Crédito,Concluído,1.000065
433,V0434,2025-01-30,São Paulo,SP,Mochila,Acessórios,1,159.9,0.10,143.91,Boleto,Cancelado,1.000000

In [ ]:
# Verificando a coluna novamente
df["quantidade"].value_counts()

quantidade
1    102
2     98
3     94
5     93
4     93
Name: count, dtype: int64

In [ ]:
# Excluindo a coluna temporaria, para comparação

df = df.drop(columns=["quantidade_esperada"])

Verificamos que dois registros possuiam quantidade iguais a 1, e outro igual a 5.

#### 3.3.2 data_venda

In [ ]:
df["data_venda"].dtype

dtype('O')

In [ ]:
df["data_venda"].value_counts()

data_venda
2025-05-22    9
2025-04-29    7
2025-03-16    7
2025-01-12    6
2025-04-28    6
             ..
02/06/2025    1
11/03/2025    1
11/05/2025    1
10/05/2025    1
02/03/2025    1
Name: count, Length: 183, dtype: int64

Encontramos a coluna com o tipo 'object' e escrita de dados de forma distinta.

In [ ]:
# Corrigindo a coluna data_venda

df["data_venda"] = pd.to_datetime(
    df["data_venda"],
    dayfirst=True,
    format="mixed",
    errors="coerce"
)

In [ ]:
# Verificando...

df["data_venda"].value_counts()

data_venda
2025-05-22    9
2025-03-16    7
2025-04-28    7
2025-04-29    7
2025-05-10    6
             ..
2025-05-23    1
2025-06-03    1
2025-01-14    1
2025-01-20    1
2025-03-02    1
Name: count, Length: 164, dtype: int64

In [ ]:
df["data_venda"].dtypes

dtype('<M8[ns]')

### 3.4 Valores inválidos numéricos
Verificação e tratamento de valores numéricos inválidos.
Em: valor_total, preco_unitario e desconto_pct

Anteriormente, através do .info(), identificamos que as colunas em questão (valor_total, preco_unitario e desconto_pct) estão com o tipo de dados float64, um tipo aceitável para nossas análises.
Sendo assim, vamos verificar alguns dados inseridos nessas colunas.

In [ ]:
# Em valor_total
df["valor_total"].value_counts()

valor_total
949.50    9
99.90     7
189.90    7
129.90    7
799.50    7
         ..
712.22    1
89.91     1
306.83    1
431.73    1
512.73    1
Name: count, Length: 151, dtype: int64

In [ ]:
# Em desconto_pct
df["desconto_pct"].value_counts()

desconto_pct
0.00    176
0.05    103
0.10    102
0.15     96
1.20      3
Name: count, dtype: int64

In [ ]:
# Em preco_unitario
df["preco_unitario"].value_counts()

preco_unitario
99.9     71
189.9    62
129.9    60
159.9    60
89.9     59
249.9    58
79.9     55
29.9     55
Name: count, dtype: int64

Percebe dois pontos de atenção:


*   Não conseguimos verificar todos os valores de valor_total, para perceber se possui erros em sua escrita
*   Há um desconto com valor 1.20, o que está incorreto, mas qual seria o valor de desconto então? Vamos ver mais adiante.

In [ ]:
# 1. Define o padrão: apenas números inteiros ou decimais com ponto.
padrao = r'^\d+(\.\d+)?$'

# 2. Identifica o que não bate com o padrão.
mascara_validos = df['valor_total'].astype(str).str.match(padrao, na=False)
erros = df[~mascara_validos]

# 3. Diagnóstico.
print(f"Total de registros fora do padrão: {len(erros)}")

if not erros.empty:
    print("\nAmostra dos valores inválidos encontrados (valores únicos):")
    display(erros['valor_total'].unique()[:20])

    print("\nVisualização das primeiras linhas completas com erro:")
    display(erros[['valor_total']].head())
else:
    print("Nenhum erro encontrado! Todos os dados estão no formato correto.")

Total de registros fora do padrão: 10

Amostra dos valores inválidos encontrados (valores únicos):

array([nan])

Visualização das primeiras linhas completas com erro:

     valor_total
0            NaN
16           NaN
90           NaN
200          NaN
290          NaN

Percebemos que o problema ocorre por valores nulos, os quais serão tratados mais adiante.

Partiremos para avaliar os valores '1.20' em desconto_pct.

Podemos prezumir que são valores errados, pois os descontos sobem de forma gradual e baixa, e um desconto de 120% geraria um valor_total negativo.

Sendo assim, devemos corrigir.

In [ ]:
# Visualizando as linhas com desconto errado...
linhas_com_desconto_errado = df[df["desconto_pct"] == 1.20]

linhas_com_desconto_errado.head()

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido
10,V0011,2025-02-26,Salvador,BA,Garrafa Térmica,Casa,3,99.9,1.2,254.75,Cartão De Débito,Concluído
150,V0151,2025-03-25,NaN,RS,Tênis,Calçados,1,249.9,1.2,237.41,Boleto,Concluído
163,V0164,2025-02-02,São Paulo,SP,Camiseta,Vestuário,3,79.9,1.2,239.70,Cartão De Crédito,Concluído

Para garantir que o valor seja o correto, podemos verificar a fórmula utilizada para calcular o valor_total:

`
valor_total = (preco_unitario * quantidade) * (1 - desconto_pct)
`

Ou melhor, uma variação dela:

`
desconto = 1 - (valor_total / (quantidade * preco_unitario))
`

In [ ]:
# Criando outra coluna temporária para comparação

df["desconto_esperado"] = (
    1 - (df["valor_total"] / (df["quantidade"] * df["preco_unitario"]))
).round(2)

In [ ]:
# Comparando com os valores errados...

df.loc[
    df["desconto_pct"] == 1.20,
    ["desconto_pct", "desconto_esperado"]
]

     desconto_pct  desconto_esperado
10            1.2               0.15
150           1.2               0.05
163           1.2               0.00

Com os valores corretos encontrados, podemos substituí-los, da mesma forma anteriormente feita.

In [ ]:
# Correção dos descontos errados...

descontos_alvo = df["desconto_pct"] == 1.20

df.loc[descontos_alvo, "desconto_pct"] = df["desconto_esperado"]

In [ ]:
# Exibição novamente

df["desconto_pct"].value_counts()

desconto_pct
0.00    177
0.05    104
0.10    102
0.15     97
Name: count, dtype: int64

Com todos os descontos corrigidos agora, podemos deletar a coluna temporária e seguir.

Alguns descontos antes podiam aparecer com valores errados, pelo valor_total estar incorreto, mas essa coluna será trata mais adiante.

In [ ]:
# Exclusão da coluna temporária

df = df.drop(columns= ["desconto_esperado"])

Mais adiante iremos recalcular o valor da coluna valor_total, para, também, conferir se os já inseridos estavam com o cálculo correto.

### 3.5 Valores nulos
Neste tópico, iremos verificar os valores nulos e decidir oque faremos com eles.

In [ ]:
df.isnull().sum()

id_venda            0
data_venda          0
cidade              8
estado              0
produto             0
categoria           0
quantidade          0
preco_unitario      0
desconto_pct        0
valor_total        10
forma_pagamento    12
status_pedido       0
dtype: int64

Encontramos ao todo 30 valores nulos (8 em cidade, 10 em valor_total e 12 em forma_pagamento).

Podemos ter a certeza de que os valores nulos em valor_total podem ser preenchidos quando revisarmos a fórmula.

Vamos olhar mais atentamente para as outras colunas antes de tomarmos uma decisão.

In [ ]:
# Em relação a coluna cidade...

cidades_nulas = df[df["cidade"].isnull()]

cidades_nulas

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido
65,V0066,2025-05-12,NaN,BA,Tênis,Calçados,1,249.9,0.05,237.41,Cartão De Débito,Concluído
89,V0090,2025-04-20,NaN,SP,Camiseta,Vestuário,3,79.9,0.15,203.75,NaN,Concluído
150,V0151,2025-03-25,NaN,RS,Tênis,Calçados,1,249.9,0.05,237.41,Boleto,Concluído
157,V0158,2025-03-19,NaN,SP,Tênis,Calçados,1,249.9,0.00,249.90,Boleto,Concluído
193,V0194,2025-01-30,NaN,PE,Garrafa Térmica,Casa,4,99.9,0.05,379.62,Boleto,Concluído
352,V0353,2025-02-06,NaN,RS,Camiseta,Vestuário,2,79.9,0.15,135.83,Boleto,Concluído
375,V0376,2025-06-27,NaN,BA,Garrafa Térmica,Casa,5,99.9,0.15,424.57,Boleto,Cancelado
417,V0418,2025-06-27,NaN,SP,Mouse,Eletrônicos,1,89.9,0.10,80.91,Cartão De Crédito,Concluído

In [ ]:
# Em relação a coluna forma_pagamento...

forma_pagamento_nulas = df[df["forma_pagamento"].isna()]

forma_pagamento_nulas

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido
89,V0090,2025-04-20,NaN,SP,Camiseta,Vestuário,3,79.9,0.15,203.75,NaN,Concluído
114,V0115,2025-03-15,Rio De Janeiro,RJ,Fone Bluetooth,Eletrônicos,5,129.9,0.15,552.07,NaN,Concluído
182,V0183,2025-05-25,Porto Alegre,RS,Camiseta,Vestuário,2,79.9,0.00,159.80,NaN,Concluído
287,V0288,2025-02-19,Porto Alegre,RS,Fone Bluetooth,Eletrônicos,5,129.9,0.10,584.55,NaN,Concluído
301,V0302,2025-01-23,Recife,PE,Garrafa Térmica,Casa,5,99.9,0.05,474.52,NaN,Concluído
314,V0315,2025-01-16,Recife,PE,Mouse,Eletrônicos,1,89.9,0.15,76.42,NaN,Concluído
340,V0341,2025-02-17,Rio De Janeiro,RJ,Tênis,Calçados,5,249.9,0.10,1124.55,NaN,Cancelado
355,V0356,2025-03-29,Campinas,SP,Garrafa Térmica,Casa,2,99.9,0.00,199.80,NaN,Concluído
362,V0363,2025-01-24,São Paulo,SP,Calça Jeans,Vestuário,3,189.9,0.15,484.25,NaN,Concluído
402,V0403,2025-02-05,Porto Alegre,RS,Garrafa Térmica,Casa,2,99.9,0.15,169.83,NaN,Concluído
455,V0456,2025-04-15,Rio De Janeiro,RJ,Caderno,Papelaria,4,29.9,0.05,113.62,NaN,Cancelado
475,V0476,2025-06-04,São Paulo,SP,Calça Jeans,Vestuário,1,189.9,0.00,189.90,NaN,Concluído

Como os valores nulos em questão (em "cidade" e "forma_pagamento") são valores textuais, preenchê-los com algum valor presente na base poderia resultar em análises erradas.
Assim como excluir as linhas com esses valores nulos poderia apagar os demais dados dessas linhas que estão corretos.
>
Diante disso, vamos adotar a aboragem de subtituí-los por um valor que represente a ausência de valores, sendo ele o "Não Informado".

In [ ]:
# Substituindo valores nulos em cidade e forma_pagamento para "Não Informado"...

df["cidade"] = df["cidade"].fillna("Não Informado")

df["forma_pagamento"] = df["forma_pagamento"].fillna("Não Informado")

In [ ]:
# Conferindo...

print(df[['cidade', 'forma_pagamento']].isna().sum())

cidade             0
forma_pagamento    0
dtype: int64

## **4. Validação**
Revisão do tratamento e correção mais técnica dos valores.

Nos passos anteriores percebemos valores nulos na coluna valor_total, além de identificarmos um valor errado em uma coluna que compõe os cálculos de como é feita. Com base nisso, devemos recalcular a coluna de valor_total, além de conferir que tudo esteja correto nela e nas demais

### 4.1 Ajustando o valor total

Iremos ajustar a coluna valor_total em seus valores (nulos e incorretos) além de garantir uma boa formatação a ela.

In [ ]:
# Revisando a coluna...
df["valor_total"].value_counts()

valor_total
949.50    9
99.90     7
189.90    7
129.90    7
799.50    7
         ..
712.22    1
89.91     1
306.83    1
431.73    1
512.73    1
Name: count, Length: 151, dtype: int64

In [ ]:
df["valor_total"].dtypes

dtype('float64')

In [ ]:
df["valor_total"].isnull().sum()

np.int64(10)

Sabemos que o cálculo do valor total se deve por:

> valor_total = quantidade * preço_unitario * (1 -
desconto_pct).

Vamos fazer uma coluna de teste para comparar os dados já inseridos.

In [ ]:
# Criando uma nova coluna para comparar...

df["valor_esperado"] = (
    df["quantidade"] * df["preco_unitario"] * (1.0 - df["desconto_pct"])
    ).round(2)

In [ ]:
df["valor_esperado"].head()

0    239.70
1     99.90
2    719.55
3    143.82
4     89.90
Name: valor_esperado, dtype: float64

In [ ]:
# Comparando as duas...
df[["valor_total","valor_esperado"]].head(15)

    valor_total  valor_esperado
0           NaN          239.70
1         99.90           99.90
2        719.55          719.55
3        143.82          143.82
4         89.90           89.90
5        116.91          116.91
6        617.02          617.02
7        479.70          479.70
8         89.70           89.70
9        949.50          949.50
10       254.75          254.75
11       215.73          215.73
12       575.64          575.64
13       424.83          424.83
14       299.70          299.70

Podemos verificar que os valores são os mesmos, exceto quando em valores nulos.

In [ ]:
# Preenchendo os espaços de valor nulo com calculado na nova coluna...

df["valor_total"] = df["valor_total"].fillna(df["valor_esperado"])

In [ ]:
# Verificando os valores nulos desta coluna novamente...

df["valor_total"].isnull().sum()

np.int64(0)

Cosneguimos remover os valores nulos, sendo assim não precisamos da coluna auxiliar.

In [ ]:
# Excluindo a coluna temporária...

df = df.drop(columns=["valor_esperado"])

### 4.2 Conferindo a base mais uma vez.
Agora que fizemos todo esse tratamento e varredura, podemos conferir os dados novamente para ter melhor clareza da base após todo o processo.

In [ ]:
# Visão geral da base
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 0 to 479
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         480 non-null    object
 1   data_venda       480 non-null    datetime64[ns]
 2   cidade           480 non-null    object
 3   estado           480 non-null    object
 4   produto          480 non-null    object
 5   categoria        480 non-null    object
 6   quantidade       480 non-null    int64
 7   preco_unitario   480 non-null    float64
 8   desconto_pct     480 non-null    float64
 9   valor_total      480 non-null    float64
 10  forma_pagamento  480 non-null    object
 11  status_pedido    480 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 64.9+ KB

In [ ]:
# Colunas e linhas...

df.shape

(480, 12)

In [ ]:
# .head() novamente

df.head(10)

,id_venda,data_venda,cidade,estado,produto,categoria,quantidade,preco_unitario,desconto_pct,valor_total,forma_pagamento,status_pedido
0,V0001,2025-02-27,Campinas,SP,Camiseta,Vestuário,3,79.9,0.00,239.70,Cartão De Crédito,Concluído
1,V0002,2025-01-24,Campinas,SP,Garrafa Térmica,Casa,1,99.9,0.00,99.90,Cartão De Crédito,Concluído
2,V0003,2025-02-26,São Paulo,SP,Mochila,Acessórios,5,159.9,0.10,719.55,Boleto,Cancelado
3,V0004,2025-03-29,Curitiba,PR,Camiseta,Vestuário,2,79.9,0.10,143.82,Cartão De Débito,Concluído
4,V0005,2025-04-08,Belo Horizonte,MG,Mouse,Eletrônicos,1,89.9,0.00,89.90,Pix,Concluído
5,V0006,2025-05-18,Porto Alegre,RS,Fone Bluetooth,Eletrônicos,1,129.9,0.10,116.91,Pix,Concluído
6,V0007,2025-05-28,Campinas,SP,Fone Bluetooth,Eletrônicos,5,129.9,0.05,617.02,Cartão De Crédito,Concluído
7,V0008,2025-03-01,São Paulo,SP,Mochila,Acessórios,3,159.9,0.00,479.70,Pix,Concluído
8,V0009,2025-04-05,Curitiba,PR,Caderno,Papelaria,3,29.9,0.00,89.70,Cartão De Débito,Concluído
9,V0010,2025-05-17,Curitiba,PR,Calça Jeans,Vestuário,5,189.9,0.00,949.50,Cartão De Crédito,Concluído

Após tudo isso, concluímos que a limpeza, tratamento e verificação estão corretas.
Podemos seguir para as análises.

## **5. EDA**
Aqui faremos análises afim de extrair insights sobre a base de dados.

### 5.1 Análises iniciais
Neste tópico fazemos análises iniciais sobre os valores numéricos.
Utilzizando .describe(), média, mediana.

In [ ]:
# Descrição inicial
# Válido apenas para os dados numéricos

df[["quantidade", "preco_unitario", "desconto_pct", "valor_total"]].describe().round(2)

       quantidade  preco_unitario  desconto_pct  valor_total
count      480.00          480.00        480.00       480.00
mean         2.95          129.36          0.06       360.06
std          1.42           63.94          0.06       271.89
min          1.00           29.90          0.00        28.40
25%          2.00           89.90          0.00       152.83
50%          3.00          114.90          0.05       284.72
75%          4.00          167.40          0.10       486.59
max          5.00          249.90          0.15      1249.50

Através do .describe() percebemos uma série de dados numéricos sobre as colunas numéricas.

Obtemos informções sobre média (mean), valores máximos e mínimos (max e min), além de uma separação dos dados em quartis, através dos % de 25 a 75, sendo que o 50% pode ser interpretado como a mediana. Como também, dados de desvio padrão (std).

Para ter os valores separados de forma mais dedicada, vamos calcular a média e a mediana em células abaixo.

In [ ]:
# Calculando a média...

media_dados = df["valor_total"].mean().round(2)

print(f"A média dos dados em valor_total é: {media_dados}")

A média dos dados em valor_total é: 360.06

In [ ]:
# Calculando a mediana...

mediana_dados = df["valor_total"].median()

print(f"A mediana dos dados em valor_total é: {mediana_dados}")

A mediana dos dados em valor_total é: 284.72

Além de termos um espaço dedicado a esses valores, também podemos afirmar que são iguais aos exibidos em .describe().

Através desses valores de média e mediana podemos identificar que o valor máximo expresso no .describe(), para a coluna valor_total, de 1249,50, é um outlier. Pois ele está muito distante da mediana, e também do 75%.

Sobre a média e mediana entre si, percebemos uma diferença de valor, porém nada extremamente acentuado (precisamente de 75,34), oque significa que os valores devem estar, em sua maioria, bem distribuídos.

In [ ]:
# Calculando o desvio padrão...

desvio_padrao = df["valor_total"].std()

print(f"O desvio padrão dos dados em valor_total é: {desvio_padrao:.2f}")

O desvio padrão dos dados em valor_total é: 271.89

Analisando o desvio padrão junto aos outros dados, percebemos uma dispersão um pouco acentuada dos valores. Visto que o desvio padrão é de 271.89 e a média é de 360.06.

### 5.2 Valores mais afundo
Neste tópico fazemos análises mais afundo, com conhecimento mais estatístico.
Quartis, IQR.

Exibiremos os quartis 1,2 e 3.

Aos quais já foram encontrados no .describe(), mas vamos colocá-los de forma mais dedicada, e depois encontrar o IQR com eles.

In [ ]:
# Calculando e exibindo os quartis...
q1 = df["valor_total"].quantile(0.25)
q2 = df["valor_total"].quantile(0.50)
q3 = df["valor_total"].quantile(0.75)

print(f"1° Quartil: {q1:.2f}")
print(f"2° Quartil: {q2:.2f}")
print(f"3° Quartil: {q3:.2f}")

1° Quartil: 152.83
2° Quartil: 284.72
3° Quartil: 486.59

Os resultados correspondem corretamente.

Reforçando que o 2° quartil corresponde a Mediana.

Além disso, analisando os quartis agora, é perceptível uma variação leve entre ele, os "saltos" entre os dados não são gritantes. Oque também confirma que o valor de 1249,50 é um outlier.

Analisaremos o IQR agora, juntamente aos limites superior e inferior.

A distância entre o 1° quartil e o 3° quartil.

In [ ]:
# Calculando o IQR...

iqr = q3 - q1

# Calculando os limites...

limite_inferior = q1 - 1.5 * iqr
limite_superior = q3 + 1.5 * iqr

# Exibindo ...

print(f"O IQR é: {iqr:.2f}")
print(f"O limite inferior é: {limite_inferior:.2f}")
print(f"O limite superior é: {limite_superior:.2f}")

O IQR é: 333.76
O limite inferior é: -347.81
O limite superior é: 987.24

Esses dados nos ajudam a encontrar outliers, que é oque faremos logo agora.

In [ ]:
# Encontrando os outliers...

outliers = df[
    (df["valor_total"] < limite_inferior) |
    (df["valor_total"] > limite_superior)
]

print(f"Quantidade de outliers: {len(outliers)}")

Quantidade de outliers: 18

In [ ]:
# Visualizando mais diretamente...

outliers[["quantidade", "produto", "preco_unitario", "valor_total"]].sort_values(by="valor_total", ascending=False)

     quantidade      produto  preco_unitario  valor_total
372           5        Tênis           249.9      1249.50
110           5        Tênis           249.9      1249.50
353           5        Tênis           249.9      1249.50
215           5        Tênis           249.9      1249.50
416           5        Tênis           249.9      1249.50
151           5        Tênis           249.9      1187.02
165           5        Tênis           249.9      1187.02
340           5        Tênis           249.9      1124.55
317           5        Tênis           249.9      1124.55
194           5        Tênis           249.9      1124.55
260           5        Tênis           249.9      1062.08
20            5        Tênis           249.9      1062.08
278           5        Tênis           249.9      1062.08
134           5        Tênis           249.9      1062.08
81            4        Tênis           249.9       999.60
91            4        Tênis           249.9       999.60
159           4        Tênis           249.9       999.60
87            5  Calça Jeans           189.9       999.50

Através da céçula acima descobrimos os outliers, além do seu valor gasto, quantidade de produtos comprados, o produto em questão e o valor do produto.

A maior parte das compras foram de tênis com quantidades 5 sendo a maioria, exceto por compras de quantidade 4 ou a compra de 5 calças jeans.

### 5.3 Contando valores
Neste tópico utilizamos o método value_counts em algumas colunas não numéricas.

Vamos separar isso por colunas:

*   Categoria
*   Produto

#### Categoria

In [ ]:
df["categoria"].value_counts(ascending=False)

categoria
Eletrônicos    119
Vestuário      117
Casa            71
Acessórios      60
Calçados        58
Papelaria       55
Name: count, dtype: int64

#### Produto

In [ ]:
df["produto"].value_counts(ascending=False)

produto
Garrafa Térmica    71
Calça Jeans        62
Fone Bluetooth     60
Mochila            60
Mouse              59
Tênis              58
Camiseta           55
Caderno            55
Name: count, dtype: int64

#### No geral...

Idenfificamos que:
* As categoria mais pedidas foram de Eletônicos e Vestuário, porém as demais possuem grande diferença quando comparadas aos dois maiores;
* O produto mais pedido foi garra_termica; os demais produtos possuem pedidos em quantidade semelhante;

### 5.4 Interligando dados
Neste tópico utilizamos groupby() e agg() entre as colunas.

In [ ]:
df.groupby("categoria")["valor_total"].sum().sort_values(ascending=False)

categoria
Vestuário      45779.19
Calçados       40019.08
Eletrônicos    32858.20
Acessórios     28597.14
Casa           21029.04
Papelaria       4547.75
Name: valor_total, dtype: float64

Segundo a célula acima, a categoria de Vestuário foi a que mais gerou faturamento, enquanto a menos rentável (bem menos que as demais) foi papelaria.

Mas podemos ir mais a fundo...

In [ ]:
resumo_categoria = (
    df.groupby("categoria")
    .agg(
        numero_vendas=("id_venda", "count"),
        unidades_vendidas=("quantidade", "sum"),
        faturamento_total=("valor_total", "sum"),
        ticket_medio = ("valor_total", "mean")
    )
    .sort_values("faturamento_total", ascending=False)
)

resumo_categoria

             numero_vendas  unidades_vendidas  faturamento_total  ticket_medio
categoria
Vestuário              117                350           45779.19    391.275128
Calçados                58                172           40019.08    689.984138
Eletrônicos            119                318           32858.20    276.119328
Acessórios              60                190           28597.14    476.619000
Casa                    71                225           21029.04    296.183662
Papelaria               55                162            4547.75     82.686364

Através da célula acima, alguns detalhes ficam mais claros.

Vimos novamente o quanto cada categoria apareceu, porém sabemos que Vestuário vendeu mais produtos do que Eletrônicos, aidnda, rendeu mais faturamento no final, em decorrência da maior quantidade.

A categoria de Papelaria foi a que rendeu menor faturamento, possivelmente por ter os menores preços por produto.

## **6. Conclusões**
Respostas das perguntas e interpretação dos resultados.

### Pergunta 1:
1. Qual categoria apresentou o maior faturamento?

In [ ]:
maior_faturamento = (
    df.groupby("categoria")
    .agg(
        faturamento_total=("valor_total", "sum")
    )
    .sort_values("faturamento_total", ascending=False)
)

maior_faturamento

             faturamento_total
categoria
Vestuário             45779.19
Calçados              40019.08
Eletrônicos           32858.20
Acessórios            28597.14
Casa                  21029.04
Papelaria              4547.75

Baseado na célula acima, a categoria que apresentou o maior faturamento foi a de Vestuário, com R$45.779,19.

### Pergunta 2:
2. Qual forma de pagamento foi mais utilizada?

In [ ]:
forma_pagamento_mais_usada = df["forma_pagamento"].value_counts(ascending=False)

forma_pagamento_mais_usada

forma_pagamento
Boleto               125
Cartão De Crédito    124
Cartão De Débito     114
Pix                  105
Não Informado         12
Name: count, dtype: int64

Segundo a célula acima, a forma de pagamento mais utilizada foi a de Boleto.

### Pergunta 3:
3. Qual é a média e qual é a mediana do valor das vendas?

In [ ]:
print("Reutilzando código de células...")
print(f"Média dos dados: {media_dados}")
print(f"Mediana dos dados: {mediana_dados}")

Reutilzando código de células...
Média dos dados: 360.06
Mediana dos dados: 284.72

Graças ao código de células anteriores, calculamos que (baseado na coluna valor_total) a Média é 360,06 e a Mediana é 284,72.

### Pergunta 4:
4. Qual categoria apresenta o maior ticket médio?

In [ ]:
# Calculando o ticket médio por categoria...
ticket_medio_categoria = (
    df.groupby("categoria")["valor_total"]
    .mean()
    .sort_values(ascending=False)
).round(2)

ticket_medio_categoria

categoria
Calçados       689.98
Acessórios     476.62
Vestuário      391.28
Casa           296.18
Eletrônicos    276.12
Papelaria       82.69
Name: valor_total, dtype: float64

De acordo com o ticket médio calculado acima: as vendas de calçados rendem mais.

Isso pode vir em decorrência dos outliers, pelas compras com alto gasto. Ainda, vemos que papelaria rende bem menos do que as demais, provavelmente devido ao baixo custo de seus produtos. Enquanto as outras apresentam uma ordem descresente de: acessórios, vestuário, casa e eletrônicos.

### Pergunta 5:
5. Existem vendas muito acima do padrão da base? Justifique utilizando o IQR.

Sim, baseado no que encontramos no tópico 5 (EDA), identificamos o iqr no valor de 333,76, apartir dele, encontramos os limites inferior e superior (respectivamente, -347.81 e 987.24) para localizarmos com precisão a presença de outliers.

Apartir disso, localizamos 18 outliers (como também já foi mostrado um pouco com o .describe()), com valores acima do limite superior.

### Pergunta 6:
6. Quais são as principais conclusões que podem ser obtidas a partir da base tratada?

Segundo a base de dados em questão, ela corresponde a uma loja que vende diversos produtos à várias cidades e estados brasileiros.

Através do que foi analisado, conluímos que: a categoria com maior faturamento é a de `Vestuário`, enquanto a de `Papelaria` é a de menor faturamento. Isso provavelmente se deve a diferença do preço unitário dos produtos, sua quantia de pedidos e a quantidade pedida.  
Entretanto, de forma individual, o que mais gerou faturamento foi a compra de várias quantidades de tênis, sendo esses dados, os outliers da base.

Por fim, dentre as formas de pagamento, percebe-se que Boleto e Cartão de Crédito foras as mais utilizadas, com uma diferença baixíssima entre elas.

## **7. Exportação**
Exportação da base de dados após todo o processo realizado.

Após todo o processo, devemos salvar a base de dados.

In [ ]:
df.to_csv("dados_finais.csv", index=False)